### ISSUE TITLE
[Issue] Routing 

### ISSUE THREAD

**Issue by hirenvadher954** [fluttertutorialin/clean_architecture#1]
I'm not sure if you're working right now, but I discovered a flaw in your code while reviewing it. When we tap on the button in otp_verify _page.dart, nothing happens. So, how do users get to the dashboard page? If I'm mistaken, please correct me. And Thank you for sharing it with the open source community.

**Comment by fluttertutorialin** [comment]
Yes, I am working now. I will be update as soon as possible.

**Comment by hirenvadher954** [comment]
> Yes, I am working now. I will be updated as soon as possible.

If that's the case, I'll close the issue.

**Comment by fluttertutorialin** [comment]
Solved this issue.

**Comment by hirenvadher954** [comment]
I guess the issue is still present so let me clarify again.

1. When I select Login with Mobile and enter my mobile number, I am redirected to the OTP verification page, where nothing happens because there is no implementation for that. Attaching a screenshot for reference.
![Screenshot from 2022-02-13 17-23-11](https://user-images.githubusercontent.com/47621081/153751910-26149250-85bf-46b5-8dcf-bfa4c69d26ab.png)

2. Whenever I enter a username & password it always shows like this "Check my internet connection". It's probably because baseUrl & loginUrl variable are empty.
![Screenshot from 2022-02-13 17-32-32](https://user-images.githubusercontent.com/47621081/153752170-8981ccf4-1017-4080-907f-7f5a2117b099.png)

**Comment by fluttertutorialin** [comment]
Please set your base url api.

**Comment by fluttertutorialin** [comment]
This application not set base api url.

**Comment by hirenvadher954** [comment]
Thanks, I got it.
